version: '3'

services:
  db:
    image: postgres:14.0-alpine
    env_file: .env
    ports:
    - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_postgres:
  pgadmin-data: